web:
    build: .
    command: python -u app.py
    ports:
      - "80:80"
    volumes:
      - .:/todo
    links:
      - db
  db:
     image: mongo:latest
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: rootpassword
     ports:
       - 27017:27017
     volumes:
       - mongodb_data_container:/data/db
  